services:
  db:
    image: mysql:latest
    container_name: fintrack-db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: DbFinTrack
    ports:
      - "3306:3306"
    volumes:
      - fintrack-data:/var/lib/mysql

volumes:
  fintrack-data:
